---
title: "regression_HW"
author: "Reka Solymosi"
date: "20 November 2016"
output: html_document
---

##Week 6: Regression

###Part 1

For this first exercise we use data made available by StatSci.Org, an Australian organisation that among other things, makes it easy to access teaching datasets. Please download the data from [here](http://www.statsci.org/data/general/uscrime.txt).

Description of the data

Criminologists are interested in the effect of punishment regimes on crime rates. This has been studied using aggregate data on 47 states of the USA for 1960. The data set contains the following columns:
 
  **Variable  	  	Description**
  
	M 		percentage of males aged 14-24 in total state population 
	So 		indicator variable for a southern state 
	Ed 		mean years of schooling of the population aged 25 years or over 
	Po1 		per capita expenditure on police protection in 1960 
	Po2 		per capita expenditure on police protection in 1959 
	LF 		labour force participation rate of civilian urban males in the age-group 14-24 
	M.F 		number of males per 100 females 
	Pop 		state population in 1960 in hundred thousands 
	NW 		percentage of nonwhites in the population 
	U1 		unemployment rate of urban males 14-24 
	U2 		unemployment rate of urban males 35-39 
	Wealth 		wealth: median value of transferable assets or family income 
	Ineq 		income inequality: percentage of families earning below half the median income 
	Prob 		probability of imprisonment: ratio of number of commitments to number of offenses 
	Time 		average time in months served by offenders in state prisons before their first release 
	Crime 		crime rate: number of offenses per 100,000 population in 1960 

Source
Ehrlich, I. (1973) Participation in illegitimate activities: a theoretical and empirical investigation. Journal of Political Economy 81, 521-565.

1.	You need to select 4 different explanatory variables to model crime with this observational dataset. You need to use common sense and technical knowledge in making your selection. 

2.	You need to fit the model, diagnose it, introduce any corrections to it you think are needed, interpret it and discuss it.


###Part 2

Use the BCS0708 dataset.

1.	Select 4 variables as explanatory inputs in a model oriented to predict victimisation. There's a limited choice of variables, so your model won't be great. 

2.	You need to fit the model, diagnose it, introduce any corrections to it you think are needed, interpret it and discuss it.

