---
title: "Resources"
output: 
  html_document:
    theme: cosmo
    highlight: haddock
---

It has never been easier to learn R. There is an increasing abundance of materials available for students and professional analysts. As R becomes more and more popular, the wealth of resources is only likely to increase.

**Table of contents**

[Textbooks](#books-of-the-introductory-kind)

[Video lectures series](#video-lecture-series)

[Interactive tools](#interactive-tools)

[MOOCS](#moocs)


###Books (of the introductory kind)

If you are a British student in a social science degree my top of the list recommendations are Field, Miles and Field and Winston Chang.

+ [Field, Miles and Field 2012 "Discovering Statistics Using R"](http://www.sagepub.com/dsur/main.htm). This 992 pages volume is a pretty good place to start learning the R programming language. You are unlikely to go through all the techniques covered on it for an intro level course. But the later chapters may help you in more advanced 3rd year level or PG courses. It is a bit overly verbose and you have to like Andy's childish humour. I do. I am childish too. Equally, his Chapter 2 "Everything you ever wanted to know about statistics" doesn't cut it for me. I think one needs firmer foundations introduced in a more rigorous manner (easy for me to say!). I think we focus too much on teaching tests rather than foundations. Also, as psychologist his examples and selection of techniques works better for psychology students. Regarding the latter I would have appreciated, at the very least, a bit more discussion of survey data analysis, and particularly a bit more focus on cross tabulations and measures of association appropriate when studying relationships between factor variables (rather than simply discusing chi square). Hopefully the second edition will focus on RStudio. Nonetheless, you are not going to find anything as comprehensive and appropriately tailored for social science UG and entry level PG students. 

+ [Chang 2012 R Graphics Cookbook](http://shop.oreilly.com/product/0636920023135.do). This wonderful recipes for producing data visualisations with (primarily) `ggplot2` is second to none. It has never left my desk since I bought it. If you are going to be doing graphics with R, I do strongly suggest you purchase what will be one of the most used reference books in your personal library.

Two other books one may want to consider (for different reasons) are:

+ [Gerbing 2013 R Data Analysis without Programming](http://www.routledge.com/articles/r_data_analysis_without_programming/). Well, the title is not truly accurate. This is not a book that teaches a drop-down-menu GUI for doing data analysis without using code. You still use code, but via the `lessR` package that tries to reduce the amount of coding an intro level student may have to do. In this is similar in philosophy to the `mosaic` package. It's much shorter (and about 15 pounds cheaper) than the Field et al book and it focuses on intro level type of techniques. But then it does not cover some of the more advanced techniques discussed (e.g., multilevel analysis) in the Field book.

+ [Kaplan  2012 Statistical modeling: A fresh approach](http://www.mosaic-web.org/go/StatisticalModeling/). This is not written for social science students. Yet it represents an interesting take on trying to introduce statistics. Better at the foundational stuff than Field. The focus is on teaching statistical reasoning rather than R. But it is a product linked to the mosaic project, funded by the National Science Foundation, and like the previous book aims to introduce R via minimal coding (using the `mosaic` package). I very much like aspects of the teaching philosophy underpinning this project. 

Finally, they are not books stricto sensu but [Quick R](http://www.statmethods.net/) and the [R Cookbook](http://www.cookbook-r.com/) are possibly the pages you will visit the most as you try to figure out how to do things with R.

###Video lecture series

There are two in particular worth keeping an eye on. They can be used as part of a blended learning experience. Camtasia is great, but why produce something that is already out there?

+ [Mike Marin series of videos](https://www.youtube.com/playlist?list=PLqzoL9-eJTNATicffatWXTEjwMq6N0Sf3) This is excellent for something done outside a MOOC. The production values are very good. And a lot of effort has been put into it. Mike lectures at the School of Population and Public Health at the University of British Columbia. Highly recommended.

+ [Elementary Statistics with R](https://www.youtube.com/user/GCstats). This is a full video lecture course on elementary statistics that was created and developed at Georgetown College in Kentucky. They also use the `mosaic` package as part of this course. I have not seen the whole series of videos, but the ones I have are pretty decent. I use them (combined with other materials) for my teaching as part of the flipped classroom experience. 

+ [R Twotorials](http://www.twotorials.com/). Who doesn't know this? Anthony D'amico has done us all a great service. But if you are totally new to R you may find the pace of delivery a bit intimidating. It is though a helpful resource for quickly learning how to do particular bits.

+ [This list of video resources by Jeromy Anglim](http://jeromyanglim.blogspot.co.uk/2010/05/videos-on-data-analysis-with-r.html) is about 4 years old, but I have not seen anything similar elsewhere.

###Interactive tools

By this I mean IT based applications that teach you R.

+ [swirl](http://swirlstats.com/) is a package that allows educators to produce teaching modules for learning R. You install this package (which come with some modules) and may install additional modules from [GitHub](https://github.com/swirldev/swirl_courses). Once installed you can learn R, within R. Cool. Just follow the instructions in the webpage

+ [datacamp](https://www.datacamp.com/) has adapted this technology to develop a series of online interactive tutorials. Basically you will be interacting with R via the web. But the principles are the same. At the moment they have three different courses. This is linked to [OpenIntro](http://www.openintro.org/stat/labs.php?stat_book=os), which also allow you to go through the foundational course using swirl in your local machine. 

+ [Try R](http://tryr.codeschool.com/) O'Reilly also has a free interactive course. More focused on the programming side of things than the statistics, but worth a try (no pun intented).

###MOOCS

Pretty much all data analysis MOOCS use R. So it is a wonderful set of resources for skilling you up using R.

+ [Data Analysis with R UDACITY](https://www.udacity.com/course/ud651). I did this one when it was called Exploratory Data Analysis. I loved it. I love the focus on data visualisation through the course and that there's much less focus on statistical inference. It is very hands on. The production values are excellent. Relies on `ggplot2`. And you can do it for free (click free trial) at your own pace. Only "but" is the very annoying in your face Facebook product placement (they teach the course so I guess you just have to live with that). It is highly recommended.

+ [Data science track specialisation in COURSERA](https://www.coursera.org/specialization/jhudatascience/1?utm_medium=listingPage). Taught by Jeff Leek, Roger Peng and Brian Caffo from Johhn Hopkins University. They were the fist to try this. Their older courses are available in Jeff and Roger youtube channels. They have repacked those courses, added new material, and now what you have is a collection of courses running in a regular monthly basis. It is much more about the video lecturing than the UDACITY course. I thought they rushed a bit some of the video lectures for early iterations of some of the newer courses. But this is still a great resource that will keep improving.

+ [Data Analysis and Statistical Inference in Coursera](https://www.coursera.org/course/statistics). Possibly a better entry point for UG students than the John Hopkins courses. If you have good students that have done well in stats and want to push them to something higher (like learning R), you should consider recommending them to do this course. It covers similar ground to an intro level course (at least in the USA) and will help to reinforce concepts, plus they will learn R. The instructor collaborates with OpenIntro and there is interactive labs that I already mentioned that go alongside this course. They use the free online OpenIntro textbook.

+ [Explore Statistics with R](https://www.edx.org/course/kix/kix-kiexplorx-explore-statistics-r-1524#.VAhZ__ldWPU). This is the new kid in the hood. Starts September 2014. I cannot say much about it yet. But it will be interesting to see how it develops.